//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.ServicioPedidos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.org/", ConfigurationName="ServicioPedidos.ServicioPedidos")]
    public interface ServicioPedidos {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.org/ServicioPedidos/ObtenerPedidosRequest", ReplyAction="http://servicios.org/ServicioPedidos/ObtenerPedidosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoFinal.ServicioPedidos.ObtenerPedidosResponse ObtenerPedidos(ProyectoFinal.ServicioPedidos.ObtenerPedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.org/ServicioPedidos/ObtenerPedidosRequest", ReplyAction="http://servicios.org/ServicioPedidos/ObtenerPedidosResponse")]
        System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.ObtenerPedidosResponse> ObtenerPedidosAsync(ProyectoFinal.ServicioPedidos.ObtenerPedidosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.org/ServicioPedidos/actualizarPedidoRequest", ReplyAction="http://servicios.org/ServicioPedidos/actualizarPedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoFinal.ServicioPedidos.actualizarPedidoResponse actualizarPedido(ProyectoFinal.ServicioPedidos.actualizarPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.org/ServicioPedidos/actualizarPedidoRequest", ReplyAction="http://servicios.org/ServicioPedidos/actualizarPedidoResponse")]
        System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.actualizarPedidoResponse> actualizarPedidoAsync(ProyectoFinal.ServicioPedidos.actualizarPedidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.org/ServicioPedidos/insertarPedidoRequest", ReplyAction="http://servicios.org/ServicioPedidos/insertarPedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoFinal.ServicioPedidos.insertarPedidoResponse insertarPedido(ProyectoFinal.ServicioPedidos.insertarPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.org/ServicioPedidos/insertarPedidoRequest", ReplyAction="http://servicios.org/ServicioPedidos/insertarPedidoResponse")]
        System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.insertarPedidoResponse> insertarPedidoAsync(ProyectoFinal.ServicioPedidos.insertarPedidoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.org/ServicioPedidos/ObtenerTipoPedidoRequest", ReplyAction="http://servicios.org/ServicioPedidos/ObtenerTipoPedidoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoResponse ObtenerTipoPedido(ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.org/ServicioPedidos/ObtenerTipoPedidoRequest", ReplyAction="http://servicios.org/ServicioPedidos/ObtenerTipoPedidoResponse")]
        System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoResponse> ObtenerTipoPedidoAsync(ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.org/")]
    public partial class modelPedido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string colaboradorField;
        
        private string comentarioField;
        
        private string descripcion_pedidoField;
        
        private string direccion_destinoField;
        
        private string direccion_origenField;
        
        private string estadoField;
        
        private string fecha_ingresoField;
        
        private int idEstadoField;
        
        private int idPedidoField;
        
        private int idUsuarioField;
        
        private int id_colaboradorField;
        
        private int tipo_pedidoField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string colaborador {
            get {
                return this.colaboradorField;
            }
            set {
                this.colaboradorField = value;
                this.RaisePropertyChanged("colaborador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion_pedido {
            get {
                return this.descripcion_pedidoField;
            }
            set {
                this.descripcion_pedidoField = value;
                this.RaisePropertyChanged("descripcion_pedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string direccion_destino {
            get {
                return this.direccion_destinoField;
            }
            set {
                this.direccion_destinoField = value;
                this.RaisePropertyChanged("direccion_destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string direccion_origen {
            get {
                return this.direccion_origenField;
            }
            set {
                this.direccion_origenField = value;
                this.RaisePropertyChanged("direccion_origen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                this.fecha_ingresoField = value;
                this.RaisePropertyChanged("fecha_ingreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idEstado {
            get {
                return this.idEstadoField;
            }
            set {
                this.idEstadoField = value;
                this.RaisePropertyChanged("idEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int idPedido {
            get {
                return this.idPedidoField;
            }
            set {
                this.idPedidoField = value;
                this.RaisePropertyChanged("idPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int id_colaborador {
            get {
                return this.id_colaboradorField;
            }
            set {
                this.id_colaboradorField = value;
                this.RaisePropertyChanged("id_colaborador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int tipo_pedido {
            get {
                return this.tipo_pedidoField;
            }
            set {
                this.tipo_pedidoField = value;
                this.RaisePropertyChanged("tipo_pedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPedidos", WrapperNamespace="http://servicios.org/", IsWrapped=true)]
    public partial class ObtenerPedidosRequest {
        
        public ObtenerPedidosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerPedidosResponse", WrapperNamespace="http://servicios.org/", IsWrapped=true)]
    public partial class ObtenerPedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoFinal.ServicioPedidos.modelPedido[] @return;
        
        public ObtenerPedidosResponse() {
        }
        
        public ObtenerPedidosResponse(ProyectoFinal.ServicioPedidos.modelPedido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPedido", WrapperNamespace="http://servicios.org/", IsWrapped=true)]
    public partial class actualizarPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int IdPedido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int IdEstado;
        
        public actualizarPedidoRequest() {
        }
        
        public actualizarPedidoRequest(int IdPedido, int IdEstado) {
            this.IdPedido = IdPedido;
            this.IdEstado = IdEstado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPedidoResponse", WrapperNamespace="http://servicios.org/", IsWrapped=true)]
    public partial class actualizarPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public actualizarPedidoResponse() {
        }
        
        public actualizarPedidoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPedido", WrapperNamespace="http://servicios.org/", IsWrapped=true)]
    public partial class insertarPedidoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ID_USUARIO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TIPO_PEDIDO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIR_ORIGEN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DIR_DESTINO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COMENTARIO;
        
        public insertarPedidoRequest() {
        }
        
        public insertarPedidoRequest(int ID_USUARIO, int TIPO_PEDIDO, string DIR_ORIGEN, string DIR_DESTINO, string COMENTARIO) {
            this.ID_USUARIO = ID_USUARIO;
            this.TIPO_PEDIDO = TIPO_PEDIDO;
            this.DIR_ORIGEN = DIR_ORIGEN;
            this.DIR_DESTINO = DIR_DESTINO;
            this.COMENTARIO = COMENTARIO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPedidoResponse", WrapperNamespace="http://servicios.org/", IsWrapped=true)]
    public partial class insertarPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertarPedidoResponse() {
        }
        
        public insertarPedidoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTipoPedido", WrapperNamespace="http://servicios.org/", IsWrapped=true)]
    public partial class ObtenerTipoPedidoRequest {
        
        public ObtenerTipoPedidoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTipoPedidoResponse", WrapperNamespace="http://servicios.org/", IsWrapped=true)]
    public partial class ObtenerTipoPedidoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProyectoFinal.ServicioPedidos.modelPedido[] @return;
        
        public ObtenerTipoPedidoResponse() {
        }
        
        public ObtenerTipoPedidoResponse(ProyectoFinal.ServicioPedidos.modelPedido[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioPedidosChannel : ProyectoFinal.ServicioPedidos.ServicioPedidos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPedidosClient : System.ServiceModel.ClientBase<ProyectoFinal.ServicioPedidos.ServicioPedidos>, ProyectoFinal.ServicioPedidos.ServicioPedidos {
        
        public ServicioPedidosClient() {
        }
        
        public ServicioPedidosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPedidosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPedidosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPedidosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinal.ServicioPedidos.ObtenerPedidosResponse ProyectoFinal.ServicioPedidos.ServicioPedidos.ObtenerPedidos(ProyectoFinal.ServicioPedidos.ObtenerPedidosRequest request) {
            return base.Channel.ObtenerPedidos(request);
        }
        
        public ProyectoFinal.ServicioPedidos.modelPedido[] ObtenerPedidos() {
            ProyectoFinal.ServicioPedidos.ObtenerPedidosRequest inValue = new ProyectoFinal.ServicioPedidos.ObtenerPedidosRequest();
            ProyectoFinal.ServicioPedidos.ObtenerPedidosResponse retVal = ((ProyectoFinal.ServicioPedidos.ServicioPedidos)(this)).ObtenerPedidos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.ObtenerPedidosResponse> ProyectoFinal.ServicioPedidos.ServicioPedidos.ObtenerPedidosAsync(ProyectoFinal.ServicioPedidos.ObtenerPedidosRequest request) {
            return base.Channel.ObtenerPedidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.ObtenerPedidosResponse> ObtenerPedidosAsync() {
            ProyectoFinal.ServicioPedidos.ObtenerPedidosRequest inValue = new ProyectoFinal.ServicioPedidos.ObtenerPedidosRequest();
            return ((ProyectoFinal.ServicioPedidos.ServicioPedidos)(this)).ObtenerPedidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinal.ServicioPedidos.actualizarPedidoResponse ProyectoFinal.ServicioPedidos.ServicioPedidos.actualizarPedido(ProyectoFinal.ServicioPedidos.actualizarPedidoRequest request) {
            return base.Channel.actualizarPedido(request);
        }
        
        public bool actualizarPedido(int IdPedido, int IdEstado) {
            ProyectoFinal.ServicioPedidos.actualizarPedidoRequest inValue = new ProyectoFinal.ServicioPedidos.actualizarPedidoRequest();
            inValue.IdPedido = IdPedido;
            inValue.IdEstado = IdEstado;
            ProyectoFinal.ServicioPedidos.actualizarPedidoResponse retVal = ((ProyectoFinal.ServicioPedidos.ServicioPedidos)(this)).actualizarPedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.actualizarPedidoResponse> ProyectoFinal.ServicioPedidos.ServicioPedidos.actualizarPedidoAsync(ProyectoFinal.ServicioPedidos.actualizarPedidoRequest request) {
            return base.Channel.actualizarPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.actualizarPedidoResponse> actualizarPedidoAsync(int IdPedido, int IdEstado) {
            ProyectoFinal.ServicioPedidos.actualizarPedidoRequest inValue = new ProyectoFinal.ServicioPedidos.actualizarPedidoRequest();
            inValue.IdPedido = IdPedido;
            inValue.IdEstado = IdEstado;
            return ((ProyectoFinal.ServicioPedidos.ServicioPedidos)(this)).actualizarPedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinal.ServicioPedidos.insertarPedidoResponse ProyectoFinal.ServicioPedidos.ServicioPedidos.insertarPedido(ProyectoFinal.ServicioPedidos.insertarPedidoRequest request) {
            return base.Channel.insertarPedido(request);
        }
        
        public bool insertarPedido(int ID_USUARIO, int TIPO_PEDIDO, string DIR_ORIGEN, string DIR_DESTINO, string COMENTARIO) {
            ProyectoFinal.ServicioPedidos.insertarPedidoRequest inValue = new ProyectoFinal.ServicioPedidos.insertarPedidoRequest();
            inValue.ID_USUARIO = ID_USUARIO;
            inValue.TIPO_PEDIDO = TIPO_PEDIDO;
            inValue.DIR_ORIGEN = DIR_ORIGEN;
            inValue.DIR_DESTINO = DIR_DESTINO;
            inValue.COMENTARIO = COMENTARIO;
            ProyectoFinal.ServicioPedidos.insertarPedidoResponse retVal = ((ProyectoFinal.ServicioPedidos.ServicioPedidos)(this)).insertarPedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.insertarPedidoResponse> ProyectoFinal.ServicioPedidos.ServicioPedidos.insertarPedidoAsync(ProyectoFinal.ServicioPedidos.insertarPedidoRequest request) {
            return base.Channel.insertarPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.insertarPedidoResponse> insertarPedidoAsync(int ID_USUARIO, int TIPO_PEDIDO, string DIR_ORIGEN, string DIR_DESTINO, string COMENTARIO) {
            ProyectoFinal.ServicioPedidos.insertarPedidoRequest inValue = new ProyectoFinal.ServicioPedidos.insertarPedidoRequest();
            inValue.ID_USUARIO = ID_USUARIO;
            inValue.TIPO_PEDIDO = TIPO_PEDIDO;
            inValue.DIR_ORIGEN = DIR_ORIGEN;
            inValue.DIR_DESTINO = DIR_DESTINO;
            inValue.COMENTARIO = COMENTARIO;
            return ((ProyectoFinal.ServicioPedidos.ServicioPedidos)(this)).insertarPedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoResponse ProyectoFinal.ServicioPedidos.ServicioPedidos.ObtenerTipoPedido(ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoRequest request) {
            return base.Channel.ObtenerTipoPedido(request);
        }
        
        public ProyectoFinal.ServicioPedidos.modelPedido[] ObtenerTipoPedido() {
            ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoRequest inValue = new ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoRequest();
            ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoResponse retVal = ((ProyectoFinal.ServicioPedidos.ServicioPedidos)(this)).ObtenerTipoPedido(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoResponse> ProyectoFinal.ServicioPedidos.ServicioPedidos.ObtenerTipoPedidoAsync(ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoRequest request) {
            return base.Channel.ObtenerTipoPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoResponse> ObtenerTipoPedidoAsync() {
            ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoRequest inValue = new ProyectoFinal.ServicioPedidos.ObtenerTipoPedidoRequest();
            return ((ProyectoFinal.ServicioPedidos.ServicioPedidos)(this)).ObtenerTipoPedidoAsync(inValue);
        }
    }
}
